# pnpm-workspace.yaml
packages:
  # all packages in sub dirs of apps/
  - 'apps/**'
  # all packages in sub dirs of libs/
  - 'libs/**'
  # all packages in sub dirs of storybook/
  - 'docs/**'
  # exclude packages that are inside test directories
  - '!**/test/**'